# Aula 4 - Exercícios - Agregação com Pandas e Conceitos de Estatística
### Consulta a internet (Google, Stackoverflow e etc) liberada!!

In [2]:
# Importe a biblioteca pandas
import pandas as pd
import numpy as np

### 4.5 Escreva uma função para fazer o merge do dataset de morbidade consolidado com o dataset de população
#### O dataset da população deve ficar a esquerda e o dataset da morbidade a direita no resultado.

In [ ]:
# Dica 1: No dataset de morbidade existem valores NA representados por caracteres específicos em várias colunas 
#         do dataframe. Descubra quais são esses caracteres e especifiquei no argumento
#         na_values. Passe nesse argumento uma lista como os caracteres que devem ser 
#         interpretados como NA.
# Dica 2: No dataset de morbidade, especifique o separador, o caracter de números decimais e o tipo do dado do 
#         cod_ibge6 como str. Ou seja, dtype={'cod_ibge6': str}.
# Dica 3: No dataset de população, converta o cod_munic e cod_uf para str no momento de carregar o dataset de população,
#         usando novamente o argumento dtype. Exatamente como foi feito no exercício da aula 3.
def merge_morbidade_pop(path_pop, path_morbidade):
    """retorne o merge dos datasets de população e morbidade.
    """
    # YOUR CODE HERE
    df_morbidade = pd.read_csv(path_morbidade, sep=";", 
                           header=0, decimal=",", 
                           na_values=["-"], 
                           low_memory=False, 
                           dtype={"cod_ibge6":"str"}
    )

    df_populacao = pd.read_excel(path_pop, header=0, dtype={"cod_uf":"str", "cod_munic":"str"})
    df_populacao["cod_ibge6"] = df_populacao["cod_uf"] + df_populacao["cod_munic"].str.slice(0,-1,1)
    pd.merge(df_populacao, df_morbidade, on="cod_ibge6")

In [39]:
## Faça seus testes aqui
path_morbidade = '../../curso_ciencia_dados2020/data/originais/morbidade/consolidado/morbidade.csv'
path_pop = '../../curso_ciencia_dados2020/data/originais/populacao/estimativa_dou_2017.xlsx'




#cod_ibge6 = 1100015 110037

,uf,cod_uf,cod_munic,municipio,pop2017,cod_ibge6,Município,Internações,AIH_aprovadas,Valor_total,...,Val_serv_prof_-_compl_gestor,Valor_médio_AIH,Valor_médio_intern,Dias_permanência,Média_permanência,Óbitos,Taxa_mortalidade,mes,ano,mes_ano
0,RO,11,00015,Alta Floresta D'Oeste,25437,110001,Alta Floresta D'Oeste,149.0,149,101282.26,...,NaN,679.75,"679,75",632.0,"4,2",8.0,"5,37",Abr,2020,2020-04-01
1,RO,11,00015,Alta Floresta D'Oeste,25437,110001,Alta Floresta D'Oeste,86.0,86,42705.09,...,NaN,496.57,"496,57",257.0,"3,0",2.0,"2,33",Jun,2020,2020-06-01
2,RO,11,00015,Alta Floresta D'Oeste,25437,110001,Alta Floresta D'Oeste,133.0,133,119966.00,...,NaN,902.00,"902,00",534.0,"4,0",2.0,"1,50",Mai,2020,2020-05-01
3,RO,11,00015,Alta Floresta D'Oeste,25437,110001,Alta Floresta D'Oeste,197.0,197,91431.64,...,NaN,464.12,"464,12",645.0,"3,3",3.0,"1,52",Mar,2020,2020-03-01
4,RO,11,00015,Alta Floresta D'Oeste,25437,110001,Alta Floresta D'Oeste,197.0,197,93474.87,...,NaN,474.49,"474,49",646.0,"3,3",2.0,"1,02",Fev,2020,2020-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33345,DF,53,00108,Brasília,3039444,530010,Brasília,13103.0,13154,18503747.64,...,NaN,1406.70,"1412,18",68293.0,"5,2",656.0,"5,01",Jun,2020,2020-06-01
33346,DF,53,00108,Brasília,3039444,530010,Brasília,12872.0,12958,15398398.63,...,NaN,1188.33,"1196,27",64449.0,"5,0",455.0,"3,53",Mai,2020,2020-05-01
33347,DF,53,00108,Brasília,3039444,530010,Brasília,16779.0,16854,18324767.35,...,NaN,1087.27,"1092,13",95694.0,"5,7",572.0,"3,41",Mar,2020,2020-03-01
33348,DF,53,00108,Brasília,3039444,530010,Brasília,14566.0,14646,15961151.37,...,NaN,1089.80,"1095,78",83460.0,"5,7",453.0,"3,11",Fev,2020,2020-02-01
33349,DF,53,00108,Brasília,3039444,530010,Brasília,15827.0,15928,17707875.31,...,NaN,1111.75,"1118,84",91632.0,"5,8",578.0,"3,65",Jan,2020,2020-01-01

In [ ]:
# Validação para nota
path_morbidade = '../../curso_ciencia_dados2020/data/originais/morbidade/consolidado/morbidade.csv'
path_pop = '../../curso_ciencia_dados2020/data/originais/populacao/estimativa_dou_2017.xlsx'
test_data = {'Internações': 149, 'AIH_aprovadas': 149, 'Valor_total': 101282.26}
df_morbidade_pop = merge_morbidade_pop(path_pop, path_morbidade)
df_00015 = df_morbidade_pop[(df_morbidade_pop['mes']=='Abr') & (df_morbidade_pop['cod_munic']=='00015')]
df_00015 = df_00015.loc[:,['Internações', 'AIH_aprovadas', 'Valor_total']]
dict2 = df_00015.to_dict(orient='records')[0]
dict1 = df_morbidade_pop.iloc[0, 8:11].to_dict()
assert dict1 == test_data or dict2 == test_data